apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-server
  template:
    metadata:
      labels:
        app: board-server
    spec:
      containers:
        - name: server
          image: board-server
          imagePullPolicy: Never
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3001"
            - name: SUPABASE_URL
              value: "https://nripzvcjtoxvjzskejub.supabase.co/"
            - name: SUPABASE_ANON_KEY
              value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yaXB6dmNqdG94dmp6c2tlanViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxOTQ3NDEsImV4cCI6MjA5MDc3MDc0MX0.nni3JhjV4gLD0RRBlDBmh4E0oELqlJHDxDFPv6qZ8Eg" # ใส่รหัสเต็มจาก .env
            - name: SUPABASE_SERVICE_ROLE_KEY
              value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yaXB6dmNqdG94dmp6c2tlanViIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTE5NDc0MSwiZXhwIjoyMDkwNzcwNzQxfQ.eUWYdidW_abc07Ocodp2_ndN3Ma2YfsFZNFOmqfVM7Y" # ใส่รหัสเต็มจาก .env
            - name: CLIENT_URL
              value: "https://board.k8s.dev"
            - name: SESSION_SECRET
              value: "development-secret-key"
            - name: MAX_FILE_SIZE
              value: "20971520"
            - name: CERT_THAI_FONT_PATH
              value: "/app/fonts/THSarabunNew.ttf"
            - name: GOOGLE_CLIENT_ID
              value: "GOOGLE_CLIENT_ID"
            - name: GOOGLE_CLIENT_SECRET
              value: "GOOGLE_CLIENT_SECRET"
            - name: GOOGLE_CALLBACK_URL
              value: "https://board.k8s.dev/api/auth/google/callback"
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: board-server
spec:
  selector:
    app: board-server
  ports:
    - port: 3001
      targetPort: 3001